#!/bin/bash
#
# Quick Deploy Guide - LIFF Dynamic Documents + GCS
#

echo "🚀 LIFF Dynamic Documents + Google Cloud Storage"
echo "================================================="
echo ""
echo "✅ Pre-flight Checklist:"
echo ""
echo "  [✓] Google Cloud Storage SDK installed (composer)"
echo "  [✓] GoogleCloudStorage helper class created"
echo "  [✓] Service account key: config/gcp/service-account.json"
echo "  [✓] LIFF form updated with dynamic document fields"
echo "  [✓] Documents API updated for GCS upload"
echo "  [✓] No syntax errors in modified files"
echo ""
echo "📋 Files Modified:"
echo "  - composer.json (added google/cloud-storage)"
echo "  - includes/GoogleCloudStorage.php (NEW)"
echo "  - api/lineapp/documents.php (GCS integration)"
echo "  - liff/application-form.html (dynamic fields)"
echo "  - .env.example (GCS config)"
echo ""
echo "🎯 Ready to Deploy!"
echo ""
echo "Choose deployment method:"
echo ""
echo "  1. Quick Deploy (Recommended):"
echo "     ./deploy_liff_gcs.sh"
echo ""
echo "  2. Standard Deploy:"
echo "     ./deploy_app_to_production.sh"
echo ""
echo "  3. VS Code Task:"
echo "     Ctrl+Shift+P → 'Tasks: Run Task' → 'Deploy Autobot to production'"
echo ""
echo "📊 Post-Deployment Steps:"
echo ""
echo "  1. Run database migration:"
echo "     mysql -h <host> -u <user> -p autobot_db < migrations/add_gcs_support_to_documents.sql"
echo ""
echo "  2. Update test campaign:"
echo "     mysql -h <host> -u <user> -p autobot_db < migrations/update_demo_campaign_documents.sql"
echo ""
echo "  3. Test LIFF form:"
echo "     https://liff.line.me/<LIFF_ID>?campaign=DEMO2026"
echo ""
echo "  4. Verify GCS upload:"
echo "     gsutil ls -r gs://autobot-documents/documents/"
echo ""
echo "  5. Check logs:"
echo "     gcloud run services logs read autobot --region asia-southeast1 --limit 50"
echo ""
echo "📚 Documentation:"
echo "  - Full guide: docs/LIFF_GCS_INTEGRATION.md"
echo "  - Summary: LIFF_DYNAMIC_DOCS_GCS_SUMMARY.md"
echo ""

read -p "Press Enter to start deployment with deploy_liff_gcs.sh or Ctrl+C to cancel..."

./deploy_liff_gcs.sh
