-- Savings Accounts Table
CREATE TABLE IF NOT EXISTS savings_accounts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    account_no VARCHAR(50) UNIQUE NOT NULL,
    tenant_id VARCHAR(50) NOT NULL DEFAULT 'default',
    customer_id INT NULL,
    channel_id BIGINT UNSIGNED NOT NULL,
    external_user_id VARCHAR(255) NOT NULL,
    platform ENUM('line', 'facebook', 'web', 'instagram') NOT NULL,
    product_ref_id VARCHAR(100) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    product_price DECIMAL(12,2) NOT NULL,
    target_amount DECIMAL(12,2) NOT NULL,
    current_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    min_deposit_amount DECIMAL(12,2) NULL,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    target_date DATE NULL,
    completed_at TIMESTAMP NULL,
    status ENUM('active', 'completed', 'converted', 'cancelled', 'expired', 'refunded') NOT NULL DEFAULT 'active',
    order_id INT NULL,
    case_id BIGINT UNSIGNED NULL,
    admin_notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_account_no (account_no),
    INDEX idx_tenant (tenant_id),
    INDEX idx_customer (customer_id),
    INDEX idx_external_user (external_user_id),
    INDEX idx_product_ref (product_ref_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
